name: django

on: # Make sure 'on:' is at the root level of the YAML
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4 # Use a more recent version

      - name: Set up Python
        uses: actions/setup-python@v3 # Use a more recent version
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: | 
          pytest
